; Generated by Modular Orthodontic Wire Generator
; Date: 2025-10-05 00:51:01
; Wire Size: 0.018
; Arch Type: LOWER
; Total Wire Length: 85.32mm
; Wire Height Offset: 0.00mm
; Number of Bends: 164
; Feed Rate: 1000 mm/min
; Bend Speed: 500 mm/min
; Safety Height: 10.0mm
;
; Machine Commands:
; G0/G1 - Linear movement
; M3 - Clamp wire
; M4 - Release wire
; M5 - Bend wire
; M6 - Feed wire
;

; === INITIALIZATION ===
G21 ; Set units to millimeters
G90 ; Absolute positioning
G28 ; Home all axes
F1000 ; Set default feed rate
M117 Wire Bending Started

; === WIRE PREPARATION ===
G0 Z10.0 ; Move to safety height
G0 X10 Y0 Z10.0
G1 Z0 F500
M3 ; Clamp wire
G4 P500 ; Wait 0.5 seconds

; === BEND 1: 177.6° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X17.60 Y7.99
G1 Z-21.02 F500

; Execute bend
M5 A177.6 R12.3 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 2: 179.3° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X17.42 Y7.91
G1 Z-20.55 F500

; Execute bend
M5 A179.3 R43.4 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 3: 179.0° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X17.23 Y7.84
G1 Z-20.08 F500

; Execute bend
M5 A179.0 R30.0 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 4: 177.3° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X17.05 Y7.76
G1 Z-19.61 F500

; Execute bend
M5 A177.3 R10.8 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 5: 175.3° right ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X16.88 Y7.71
G1 Z-19.14 F500

; Execute bend
M5 A175.3 R6.2 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 6: 173.0° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X16.74 Y7.69
G1 Z-18.65 F500

; Execute bend
M5 A173.0 R4.2 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 7: 169.3° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X16.65 Y7.71
G1 Z-18.15 F500

; Execute bend
M5 A169.3 R2.7 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 8: 169.5° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X16.61 Y7.80
G1 Z-17.65 F500

; Execute bend
M5 A169.5 R2.8 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 9: 174.2° right ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X16.65 Y7.95
G1 Z-17.17 F500

; Execute bend
M5 A174.2 R5.0 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 10: 177.8° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X16.72 Y8.13
G1 Z-16.71 F500

; Execute bend
M5 A177.8 R13.2 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 11: 179.0° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X16.80 Y8.33
G1 Z-16.24 F500

; Execute bend
M5 A179.0 R29.4 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 12: 175.4° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X16.88 Y8.52
G1 Z-15.78 F500

; Execute bend
M5 A175.4 R6.3 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 13: 170.3° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X16.93 Y8.69
G1 Z-15.30 F500

; Execute bend
M5 A170.3 R3.0 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 14: 164.4° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X16.93 Y8.79
G1 Z-14.80 F500

; Execute bend
M5 A164.4 R1.9 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 15: 166.3° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X16.84 Y8.79
G1 Z-14.31 F500

; Execute bend
M5 A166.3 R2.1 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 16: 172.3° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X16.67 Y8.69
G1 Z-13.84 F500

; Execute bend
M5 A172.3 R3.7 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 17: 176.9° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X16.47 Y8.55
G1 Z-13.40 F500

; Execute bend
M5 A176.9 R9.4 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 18: 179.2° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X16.25 Y8.38
G1 Z-12.97 F500

; Execute bend
M5 A179.2 R37.6 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 19: 174.9° right ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X16.04 Y8.22
G1 Z-12.54 F500

; Execute bend
M5 A174.9 R5.7 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 20: 168.8° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.86 Y8.09
G1 Z-12.09 F500

; Execute bend
M5 A168.8 R2.6 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 21: 162.7° right ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.73 Y8.04
G1 Z-11.61 F500

; Execute bend
M5 A162.7 R1.7 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 22: 164.1° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.69 Y8.10
G1 Z-11.10 F500

; Execute bend
M5 A164.1 R1.8 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 23: 174.9° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.74 Y8.27
G1 Z-10.63 F500

; Execute bend
M5 A174.9 R5.7 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 24: 175.0° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.82 Y8.47
G1 Z-10.16 F500

; Execute bend
M5 A175.0 R5.8 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 25: 171.0° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.89 Y8.63
G1 Z-9.68 F500

; Execute bend
M5 A171.0 R3.3 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 26: 171.3° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.91 Y8.73
G1 Z-9.18 F500

; Execute bend
M5 A171.3 R3.3 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 27: 173.2° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.90 Y8.76
G1 Z-8.68 F500

; Execute bend
M5 A173.2 R4.3 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 28: 175.8° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.85 Y8.74
G1 Z-8.17 F500

; Execute bend
M5 A175.8 R6.9 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 29: 177.6° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.78 Y8.69
G1 Z-7.67 F500

; Execute bend
M5 A177.6 R12.2 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 30: 178.6° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.70 Y8.62
G1 Z-7.18 F500

; Execute bend
M5 A178.6 R20.8 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 31: 179.2° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.61 Y8.54
G1 Z-6.69 F500

; Execute bend
M5 A179.2 R37.3 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 32: 179.7° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.52 Y8.46
G1 Z-6.19 F500

; Execute bend
M5 A179.7 R84.7 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 33: 179.9° left ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.43 Y8.37
G1 Z-5.69 F500

; Execute bend
M5 A179.9 R324.9 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 34: 179.7° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.34 Y8.28
G1 Z-5.20 F500

; Execute bend
M5 A179.7 R87.2 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 35: 179.4° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.25 Y8.19
G1 Z-4.70 F500

; Execute bend
M5 A179.4 R47.1 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 36: 179.1° right ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.17 Y8.11
G1 Z-4.20 F500

; Execute bend
M5 A179.1 R31.7 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 37: 178.7° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.09 Y8.03
G1 Z-3.69 F500

; Execute bend
M5 A178.7 R23.3 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 38: 178.4° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.02 Y7.96
G1 Z-3.19 F500

; Execute bend
M5 A178.4 R17.7 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 39: 177.9° right ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.96 Y7.91
G1 Z-2.70 F500

; Execute bend
M5 A177.9 R13.7 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 40: 177.2° right ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.90 Y7.86
G1 Z-2.19 F500

; Execute bend
M5 A177.2 R10.5 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 41: 176.7° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.87 Y7.84
G1 Z-1.68 F500

; Execute bend
M5 A176.7 R8.8 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 42: 177.4° right ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.85 Y7.84
G1 Z-1.18 F500

; Execute bend
M5 A177.4 R11.5 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 43: 178.2° right ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.85 Y7.86
G1 Z-0.66 F500

; Execute bend
M5 A178.2 R16.3 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 44: 178.7° right ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.86 Y7.89
G1 Z-0.14 F500

; Execute bend
M5 A178.7 R21.9 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 45: 179.0° right ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.87 Y7.93
G1 Z0.36 F500

; Execute bend
M5 A179.0 R28.2 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 46: 179.2° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.90 Y7.97
G1 Z0.87 F500

; Execute bend
M5 A179.2 R35.7 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 47: 179.3° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.92 Y8.02
G1 Z1.38 F500

; Execute bend
M5 A179.3 R45.0 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 48: 179.5° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.96 Y8.08
G1 Z1.89 F500

; Execute bend
M5 A179.5 R57.8 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 49: 179.6° right ===
M6 S0.53 ; Feed wire 0.53mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.99 Y8.14
G1 Z2.41 F500

; Execute bend
M5 A179.6 R78.8 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 50: 179.8° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.03 Y8.20
G1 Z2.92 F500

; Execute bend
M5 A179.8 R129.6 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 51: 179.9° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.06 Y8.26
G1 Z3.42 F500

; Execute bend
M5 A179.9 R422.6 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 52: 179.6° left ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.10 Y8.32
G1 Z3.93 F500

; Execute bend
M5 A179.6 R78.3 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 53: 178.5° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.14 Y8.38
G1 Z4.44 F500

; Execute bend
M5 A178.5 R18.9 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 54: 36.2° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.16 Y8.44
G1 Z4.94 F500

; Execute bend
M5 A36.2 R0.3 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 55: 155.6° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.91 Y8.20
G1 Z4.56 F500

; Execute bend
M5 A155.6 R1.2 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 56: 178.1° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.81 Y8.08
G1 Z4.07 F500

; Execute bend
M5 A178.1 R15.3 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 57: 178.3° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.71 Y7.98
G1 Z3.58 F500

; Execute bend
M5 A178.3 R17.6 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 58: 178.2° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.63 Y7.88
G1 Z3.09 F500

; Execute bend
M5 A178.2 R16.1 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 59: 177.6° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.56 Y7.80
G1 Z2.60 F500

; Execute bend
M5 A177.6 R12.3 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 60: 176.1° right ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.50 Y7.73
G1 Z2.09 F500

; Execute bend
M5 A176.1 R7.5 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 61: 166.8° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.46 Y7.69
G1 Z1.58 F500

; Execute bend
M5 A166.8 R2.2 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 62: 160.4° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.52 Y7.71
G1 Z1.08 F500

; Execute bend
M5 A160.4 R1.5 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 63: 172.3° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.75 Y7.78
G1 Z0.62 F500

; Execute bend
M5 A172.3 R3.8 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 64: 177.3° left ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.03 Y7.87
G1 Z0.20 F500

; Execute bend
M5 A177.3 R11.1 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 65: 178.2° left ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.33 Y7.97
G1 Z-0.21 F500

; Execute bend
M5 A178.2 R16.4 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 66: 174.2° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.60 Y8.07
G1 Z-0.62 F500

; Execute bend
M5 A174.2 R5.0 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 67: 163.5° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.84 Y8.20
G1 Z-1.05 F500

; Execute bend
M5 A163.5 R1.8 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 68: 140.4° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.94 Y8.33
G1 Z-1.53 F500

; Execute bend
M5 A140.4 R0.8 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 69: 146.0° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.71 Y8.43
G1 Z-1.97 F500

; Execute bend
M5 A146.0 R0.9 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 70: 166.3° left ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X15.25 Y8.47
G1 Z-2.21 F500

; Execute bend
M5 A166.3 R2.2 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 71: 174.1° left ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.74 Y8.47
G1 Z-2.34 F500

; Execute bend
M5 A174.1 R5.0 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 72: 176.8° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X14.25 Y8.46
G1 Z-2.42 F500

; Execute bend
M5 A176.8 R9.3 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 73: 177.9° left ===
M6 S0.53 ; Feed wire 0.53mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X13.72 Y8.43
G1 Z-2.47 F500

; Execute bend
M5 A177.9 R14.8 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 74: 178.6° left ===
M6 S0.55 ; Feed wire 0.55mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X13.17 Y8.40
G1 Z-2.51 F500

; Execute bend
M5 A178.6 R21.6 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 75: 179.0° left ===
M6 S0.54 ; Feed wire 0.54mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X12.63 Y8.37
G1 Z-2.54 F500

; Execute bend
M5 A179.0 R29.7 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 76: 179.2° left ===
M6 S0.53 ; Feed wire 0.53mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X12.11 Y8.33
G1 Z-2.55 F500

; Execute bend
M5 A179.2 R39.3 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 77: 179.4° left ===
M6 S0.55 ; Feed wire 0.55mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X11.56 Y8.29
G1 Z-2.56 F500

; Execute bend
M5 A179.4 R50.4 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 78: 179.5° left ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X11.04 Y8.26
G1 Z-2.56 F500

; Execute bend
M5 A179.5 R63.7 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 79: 179.6° left ===
M6 S0.54 ; Feed wire 0.54mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X10.50 Y8.22
G1 Z-2.56 F500

; Execute bend
M5 A179.6 R79.3 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 80: 179.7° right ===
M6 S0.55 ; Feed wire 0.55mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X9.95 Y8.18
G1 Z-2.55 F500

; Execute bend
M5 A179.7 R97.6 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 81: 179.8° right ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X9.45 Y8.14
G1 Z-2.54 F500

; Execute bend
M5 A179.8 R118.3 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 82: 179.8° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X8.94 Y8.11
G1 Z-2.53 F500

; Execute bend
M5 A179.8 R140.4 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 83: 179.8° right ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X8.41 Y8.07
G1 Z-2.52 F500

; Execute bend
M5 A179.8 R162.1 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 84: 179.8° right ===
M6 S0.53 ; Feed wire 0.53mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X7.89 Y8.04
G1 Z-2.51 F500

; Execute bend
M5 A179.8 R178.6 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 85: 179.8° right ===
M6 S0.54 ; Feed wire 0.54mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X7.35 Y8.00
G1 Z-2.49 F500

; Execute bend
M5 A179.8 R184.2 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 86: 179.8° right ===
M6 S0.54 ; Feed wire 0.54mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X6.82 Y7.97
G1 Z-2.47 F500

; Execute bend
M5 A179.8 R177.4 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 87: 179.8° right ===
M6 S0.54 ; Feed wire 0.54mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X6.27 Y7.93
G1 Z-2.46 F500

; Execute bend
M5 A179.8 R162.2 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 88: 179.8° right ===
M6 S0.54 ; Feed wire 0.54mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X5.73 Y7.90
G1 Z-2.44 F500

; Execute bend
M5 A179.8 R143.9 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 89: 179.8° right ===
M6 S0.54 ; Feed wire 0.54mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X5.19 Y7.87
G1 Z-2.42 F500

; Execute bend
M5 A179.8 R125.8 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 90: 179.7° right ===
M6 S0.54 ; Feed wire 0.54mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X4.65 Y7.85
G1 Z-2.41 F500

; Execute bend
M5 A179.7 R109.3 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 91: 179.7° right ===
M6 S0.54 ; Feed wire 0.54mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X4.11 Y7.83
G1 Z-2.39 F500

; Execute bend
M5 A179.7 R94.9 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 92: 179.6° right ===
M6 S0.53 ; Feed wire 0.53mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X3.58 Y7.80
G1 Z-2.37 F500

; Execute bend
M5 A179.6 R82.4 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 93: 179.6° right ===
M6 S0.53 ; Feed wire 0.53mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X3.05 Y7.79
G1 Z-2.36 F500

; Execute bend
M5 A179.6 R71.4 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 94: 179.5° right ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X2.53 Y7.77
G1 Z-2.35 F500

; Execute bend
M5 A179.5 R61.9 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 95: 179.5° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X2.02 Y7.76
G1 Z-2.34 F500

; Execute bend
M5 A179.5 R53.5 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 96: 179.3° right ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X1.51 Y7.76
G1 Z-2.33 F500

; Execute bend
M5 A179.3 R45.8 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 97: 179.2° right ===
M6 S0.55 ; Feed wire 0.55mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X0.96 Y7.76
G1 Z-2.33 F500

; Execute bend
M5 A179.2 R39.1 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 98: 179.3° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X0.45 Y7.77
G1 Z-2.33 F500

; Execute bend
M5 A179.3 R41.5 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 99: 179.1° right ===
M6 S0.56 ; Feed wire 0.56mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-0.11 Y7.78
G1 Z-2.33 F500

; Execute bend
M5 A179.1 R36.7 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 100: 179.3° right ===
M6 S0.55 ; Feed wire 0.55mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-0.67 Y7.80
G1 Z-2.32 F500

; Execute bend
M5 A179.3 R43.5 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 101: 179.4° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-1.17 Y7.82
G1 Z-2.31 F500

; Execute bend
M5 A179.4 R51.5 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 102: 179.5° right ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-1.69 Y7.85
G1 Z-2.30 F500

; Execute bend
M5 A179.5 R60.4 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 103: 179.6° right ===
M6 S0.53 ; Feed wire 0.53mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-2.21 Y7.88
G1 Z-2.28 F500

; Execute bend
M5 A179.6 R70.8 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 104: 179.6° right ===
M6 S0.53 ; Feed wire 0.53mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-2.75 Y7.92
G1 Z-2.26 F500

; Execute bend
M5 A179.6 R83.1 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 105: 179.7° right ===
M6 S0.54 ; Feed wire 0.54mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-3.29 Y7.95
G1 Z-2.24 F500

; Execute bend
M5 A179.7 R97.5 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 106: 179.7° right ===
M6 S0.55 ; Feed wire 0.55mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-3.83 Y8.00
G1 Z-2.22 F500

; Execute bend
M5 A179.7 R114.5 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 107: 179.8° right ===
M6 S0.55 ; Feed wire 0.55mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-4.38 Y8.04
G1 Z-2.20 F500

; Execute bend
M5 A179.8 R134.0 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 108: 179.8° right ===
M6 S0.55 ; Feed wire 0.55mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-4.93 Y8.09
G1 Z-2.17 F500

; Execute bend
M5 A179.8 R154.7 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 109: 179.8° right ===
M6 S0.55 ; Feed wire 0.55mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-5.48 Y8.14
G1 Z-2.15 F500

; Execute bend
M5 A179.8 R172.6 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 110: 179.8° right ===
M6 S0.55 ; Feed wire 0.55mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-6.03 Y8.19
G1 Z-2.13 F500

; Execute bend
M5 A179.8 R181.1 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 111: 179.8° right ===
M6 S0.55 ; Feed wire 0.55mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-6.58 Y8.24
G1 Z-2.10 F500

; Execute bend
M5 A179.8 R175.3 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 112: 179.8° right ===
M6 S0.55 ; Feed wire 0.55mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-7.13 Y8.29
G1 Z-2.08 F500

; Execute bend
M5 A179.8 R157.8 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 113: 179.8° right ===
M6 S0.54 ; Feed wire 0.54mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-7.67 Y8.35
G1 Z-2.06 F500

; Execute bend
M5 A179.8 R135.5 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 114: 179.7° right ===
M6 S0.54 ; Feed wire 0.54mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-8.20 Y8.40
G1 Z-2.05 F500

; Execute bend
M5 A179.7 R113.9 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 115: 179.7° right ===
M6 S0.53 ; Feed wire 0.53mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-8.73 Y8.46
G1 Z-2.03 F500

; Execute bend
M5 A179.7 R95.0 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 116: 179.6° right ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-9.25 Y8.51
G1 Z-2.02 F500

; Execute bend
M5 A179.6 R79.0 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 117: 179.5° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-9.75 Y8.56
G1 Z-2.01 F500

; Execute bend
M5 A179.5 R65.2 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 118: 179.4° left ===
M6 S0.56 ; Feed wire 0.56mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-10.31 Y8.62
G1 Z-2.01 F500

; Execute bend
M5 A179.4 R53.4 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 119: 179.3° left ===
M6 S0.54 ; Feed wire 0.54mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-10.85 Y8.68
G1 Z-2.01 F500

; Execute bend
M5 A179.3 R43.2 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 120: 179.2° left ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-11.37 Y8.73
G1 Z-2.01 F500

; Execute bend
M5 A179.2 R34.8 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 121: 178.9° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-11.87 Y8.78
G1 Z-2.03 F500

; Execute bend
M5 A178.9 R27.6 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 122: 178.6° left ===
M6 S0.53 ; Feed wire 0.53mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-12.40 Y8.83
G1 Z-2.05 F500

; Execute bend
M5 A178.6 R21.4 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 123: 178.2° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-12.89 Y8.88
G1 Z-2.09 F500

; Execute bend
M5 A178.2 R16.0 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 124: 177.5° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-13.40 Y8.93
G1 Z-2.14 F500

; Execute bend
M5 A177.5 R11.5 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 125: 176.1° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-13.90 Y8.97
G1 Z-2.22 F500

; Execute bend
M5 A176.1 R7.6 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 126: 173.4° left ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-14.42 Y9.00
G1 Z-2.33 F500

; Execute bend
M5 A173.4 R4.5 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 127: 168.5° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-14.89 Y9.02
G1 Z-2.49 F500

; Execute bend
M5 A168.5 R2.5 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 128: 160.5° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-15.33 Y9.02
G1 Z-2.74 F500

; Execute bend
M5 A160.5 R1.5 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 129: 155.2° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-15.67 Y8.99
G1 Z-3.13 F500

; Execute bend
M5 A155.2 R1.2 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 130: 161.5° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-15.81 Y8.93
G1 Z-3.62 F500

; Execute bend
M5 A161.5 R1.6 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 131: 170.2° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-15.79 Y8.85
G1 Z-4.12 F500

; Execute bend
M5 A170.2 R3.0 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 132: 175.5° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-15.68 Y8.77
G1 Z-4.61 F500

; Execute bend
M5 A175.5 R6.6 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 133: 178.8° left ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-15.53 Y8.69
G1 Z-5.10 F500

; Execute bend
M5 A178.8 R23.8 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 134: 177.9° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-15.38 Y8.62
G1 Z-5.58 F500

; Execute bend
M5 A177.9 R13.9 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 135: 174.4° right ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-15.24 Y8.56
G1 Z-6.07 F500

; Execute bend
M5 A174.4 R5.3 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 136: 169.3° right ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-15.15 Y8.51
G1 Z-6.58 F500

; Execute bend
M5 A169.3 R2.7 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 137: 164.7° right ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-15.14 Y8.48
G1 Z-7.08 F500

; Execute bend
M5 A164.7 R1.9 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 138: 172.7° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-15.27 Y8.49
G1 Z-7.57 F500

; Execute bend
M5 A172.7 R4.0 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 139: 175.8° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-15.45 Y8.53
G1 Z-8.04 F500

; Execute bend
M5 A175.8 R6.8 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 140: 177.2° right ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-15.66 Y8.59
G1 Z-8.50 F500

; Execute bend
M5 A177.2 R10.5 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 141: 178.4° right ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-15.89 Y8.67
G1 Z-8.96 F500

; Execute bend
M5 A178.4 R18.1 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 142: 179.4° right ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-16.12 Y8.76
G1 Z-9.39 F500

; Execute bend
M5 A179.4 R47.9 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 143: 179.6° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-16.36 Y8.85
G1 Z-9.83 F500

; Execute bend
M5 A179.6 R78.5 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 144: 178.6° left ===
M6 S0.52 ; Feed wire 0.52mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-16.60 Y8.94
G1 Z-10.28 F500

; Execute bend
M5 A178.6 R20.7 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 145: 177.3° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-16.82 Y9.03
G1 Z-10.73 F500

; Execute bend
M5 A177.3 R10.8 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 146: 175.6° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-17.03 Y9.10
G1 Z-11.19 F500

; Execute bend
M5 A175.6 R6.6 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 147: 173.1° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-17.21 Y9.15
G1 Z-11.66 F500

; Execute bend
M5 A173.1 R4.2 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 148: 170.2° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-17.34 Y9.16
G1 Z-12.16 F500

; Execute bend
M5 A170.2 R3.0 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 149: 170.3° left ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-17.40 Y9.13
G1 Z-12.66 F500

; Execute bend
M5 A170.3 R3.0 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 150: 172.5° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-17.39 Y9.05
G1 Z-13.16 F500

; Execute bend
M5 A172.5 R3.9 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 151: 175.1° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-17.32 Y8.94
G1 Z-13.65 F500

; Execute bend
M5 A175.1 R6.0 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 152: 177.8° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-17.22 Y8.81
G1 Z-14.13 F500

; Execute bend
M5 A177.8 R13.0 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 153: 179.7° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-17.09 Y8.66
G1 Z-14.60 F500

; Execute bend
M5 A179.7 R88.6 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 154: 177.0° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-16.98 Y8.52
G1 Z-15.08 F500

; Execute bend
M5 A177.0 R9.6 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 155: 173.9° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-16.88 Y8.39
G1 Z-15.56 F500

; Execute bend
M5 A173.9 R4.8 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 156: 170.9° right ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-16.82 Y8.29
G1 Z-16.06 F500

; Execute bend
M5 A170.9 R3.2 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 157: 172.7° right ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-16.84 Y8.24
G1 Z-16.55 F500

; Execute bend
M5 A172.7 R4.0 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 158: 175.1° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-16.90 Y8.22
G1 Z-17.06 F500

; Execute bend
M5 A175.1 R5.9 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 159: 176.4° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-17.00 Y8.23
G1 Z-17.56 F500

; Execute bend
M5 A176.4 R8.0 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 160: 177.5° right ===
M6 S0.50 ; Feed wire 0.50mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-17.13 Y8.25
G1 Z-18.04 F500

; Execute bend
M5 A177.5 R11.6 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 161: 178.5° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-17.27 Y8.29
G1 Z-18.52 F500

; Execute bend
M5 A178.5 R19.8 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 162: 179.5° right ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-17.43 Y8.33
G1 Z-19.01 F500

; Execute bend
M5 A179.5 R60.0 DR
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 163: 179.5° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-17.59 Y8.38
G1 Z-19.49 F500

; Execute bend
M5 A179.5 R61.4 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === BEND 164: 178.5° left ===
M6 S0.51 ; Feed wire 0.51mm
G4 P200 ; Wait for wire feed

; Position bending mechanism
G0 Z10.0 ; Safety height
G0 X-17.74 Y8.43
G1 Z-19.98 F500

; Execute bend
M5 A178.5 R20.0 DL
G4 P1000 ; Wait for bend completion

; Return to safe position
G0 Z10.0

; === COMPLETION ===
M6 S0.51 ; Feed remaining wire
G4 P500 ; Wait for final feed

; Cleanup
M4 ; Release wire clamp
G0 Z10.0 ; Safety height
G28 ; Return home
M117 Wire Bending Complete

; === SUMMARY ===
; Total wire used: 85.32mm
; Total bends: 164
; Estimated time: 22.5 minutes

M30 ; Program end